# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1018, 765)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 1011, 751))
        self.stackedWidget.setObjectName("stackedWidget")
        self.p_start_window = QtWidgets.QWidget()
        self.p_start_window.setObjectName("p_start_window")
        self.label_2 = QtWidgets.QLabel(self.p_start_window)
        self.label_2.setGeometry(QtCore.QRect(480, 10, 81, 21))
        self.label_2.setObjectName("label_2")
        self.b_shah = QtWidgets.QPushButton(self.p_start_window)
        self.b_shah.setGeometry(QtCore.QRect(460, 190, 111, 41))
        self.b_shah.setObjectName("b_shah")
        self.b_calculator = QtWidgets.QPushButton(self.p_start_window)
        self.b_calculator.setGeometry(QtCore.QRect(460, 270, 111, 41))
        self.b_calculator.setObjectName("b_calculator")
        self.stackedWidget.addWidget(self.p_start_window)
        self.p_game_window = QtWidgets.QWidget()
        self.p_game_window.setObjectName("p_game_window")
        self.label = QtWidgets.QLabel(self.p_game_window)
        self.label.setGeometry(QtCore.QRect(230, 60, 601, 601))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../../Pictures/Screenshots/shah.png"))
        self.label.setObjectName("label")
        self.b_back_start_window = QtWidgets.QPushButton(self.p_game_window)
        self.b_back_start_window.setGeometry(QtCore.QRect(888, 74, 101, 41))
        self.b_back_start_window.setObjectName("b_back_start_window")
        self.stackedWidget.addWidget(self.p_game_window)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Меню"))
        self.b_shah.setText(_translate("MainWindow", "Шахматы"))
        self.b_calculator.setText(_translate("MainWindow", "Калькулятор"))
        self.b_back_start_window.setText(_translate("MainWindow", "Главное меню"))
